on: push

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        otp: ['24.0']
        elixir: ['1.13.3']
        rebar3: ['3.13.1']
    env:
      MAKE: make
      CC: gcc
      MIX_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Erlang/OTP package
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\erlang
          key: OTP-${{ matrix.otp }}-windows-2019
      - name: Cache rebar3 package
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\Elixir
          key: Rebar3-${{ matrix.rebar3 }}-windows-2019
      - name: Cache Elixir package
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\Elixir
          key: Elixir-${{ matrix.elixir }}-windows-2019
      - name: Install Erlang/OTP
        run: choco install -y erlang --version ${{ matrix.otp }}
      - name: Install Elixir
        run: choco install -y elixir --version ${{ matrix.elixir }}
      - name: Install rebar3
        run: choco install rebar3 --version ${{ matrix.rebar3 }}
      - name: Add Elixir to Path
        run: echo "C:\ProgramData\chocolatey\lib\Elixir\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Dependencies
        run: mix local.rebar --force && mix local.hex --force && mix deps.get
      - name: print dir
        run: dir
      - name: release
        run: mix release cli
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: D:\a\bert-to-json\bert-to-json\_build\prod\rel\bakeware
      - name: upload exe
        uses: actions/upload-artifact@v3
        with:
          path: bert_to_json.exe
